export default {
  lightGray: "#B3B3B3",
  listBackground: "#EEE",
  white: "#FFF",
  light: {
    primary: "#2D2D2D",
    background: "#F8F8F8",
    text: "#2D2D2D",
    textMuted: "#B3B3B3",
    inputBackground: "#E4E4E4",
    placeholder: "#B3B3B3",
    buttonBackground: "#2D2D2D",
    error: "#BD2025",
    white: "#FFF",
  },
  dark: {
    primary: "#2D2D2D",
    background: "#F8F8F8",
    text: "#2D2D2D",
    textMuted: "#B3B3B3",
    inputBackground: "#E4E4E4",
    placeholder: "#B3B3B3",
    buttonBackground: "#2D2D2D",
    error: "#BD2025",
    white: "#FFF",
  },
};
