# Dockerfile
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=ofekHanaknik
ENV POSTGRES_PASSWORD=ofekHamafkir
ENV POSTGRES_DB=mydb

# Copy the initialization script to the docker entrypoint directory
COPY init_db.sql /docker-entrypoint-initdb.d/

# The base image's entrypoint takes care of executing scripts in /docker-entrypoint-initdb.d
